apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: ingress-secret
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDbzCCAlegAwIBAgIUP5l2gO7P3p/bkfY2n2iMwTJ5lNgwDQYJKoZIhvcNAQEL
    BQAwODEaMBgGA1UEAwwRc3BhdGlhbC1kaW0tNi5vcmcxGjAYBgNVBAoMEXNwYXRp
    YWwtZGltLTYub3JnMB4XDTIzMDkyNzAyNDIxOVoXDTI0MDkyNjAyNDIxOVowODEa
    MBgGA1UEAwwRc3BhdGlhbC1kaW0tNi5vcmcxGjAYBgNVBAoMEXNwYXRpYWwtZGlt
    LTYub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1I4pwKtQkYhn
    w/oF0ktFW9XR4S7dce/1wtELCTArqSy205el8isN2VNr0jGXywGVL/iHDeRLD3S9
    CHpNyUsDSNnwl0jLvEAirNEtEOwhKJfokv0j0oKpQKdLGA2ODlQ8Tgsph8lyCDhU
    i2Elo4zSp/BP1HnWwCIL8LJiOmzVpSX/IHUwsBfmCCD+BEOo/RlFDKp9S+P0CcLJ
    fTqY9rojaEH0yyK0uQugwlXnG/kDZl3DfX34cTK0BGbc7pfFhwYF7/JCIFte4PZT
    qrxx2OEufYSHm5VXLS80GE92HkyPhbmhUWPRtAP2s26k0FgHkQp0KSJrDy5XcsXh
    fTLBrw89GQIDAQABo3EwbzAdBgNVHQ4EFgQUYQ5IFsSx6FnFsCXjivyeEW3QiUIw
    HwYDVR0jBBgwFoAUYQ5IFsSx6FnFsCXjivyeEW3QiUIwDwYDVR0TAQH/BAUwAwEB
    /zAcBgNVHREEFTATghFzcGF0aWFsLWRpbS02Lm9yZzANBgkqhkiG9w0BAQsFAAOC
    AQEANGef5/LriBC0j/yIbEvdrTKfZf0REqFwORQcB3JA+i7NFsggAVlyMgEcadC4
    89M/2aSRex1gIHHWCpWqU90u7okMbPqel20qNZcwPwGtCA//3BAYaAFNLCTFqWr4
    s/ciC/ZmvQ1R96+maP9xJTpK5vQlvsw7Ki5UnOeetOnZLKLvWmTX1a5+JeaSq8SI
    R1oeDUKI8DI1lN5xurSP+rcr0AltRPUganSetESZKAE1rFPiQH5OB6RDpmKGauhA
    GR0L+eXx6c0q2D1EXD7/vz8u8fE3nUg8jHcfnuZ+7J6xyGKkqrrpwp0mQOoHx3m6
    O8FyjYXXTKlb/XQjBtdmDR0Qqg==
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDUjinAq1CRiGfD
    +gXSS0Vb1dHhLt1x7/XC0QsJMCupLLbTl6XyKw3ZU2vSMZfLAZUv+IcN5EsPdL0I
    ek3JSwNI2fCXSMu8QCKs0S0Q7CEol+iS/SPSgqlAp0sYDY4OVDxOCymHyXIIOFSL
    YSWjjNKn8E/UedbAIgvwsmI6bNWlJf8gdTCwF+YIIP4EQ6j9GUUMqn1L4/QJwsl9
    Opj2uiNoQfTLIrS5C6DCVecb+QNmXcN9ffhxMrQEZtzul8WHBgXv8kIgW17g9lOq
    vHHY4S59hIeblVctLzQYT3YeTI+FuaFRY9G0A/azbqTQWAeRCnQpImsPLldyxeF9
    MsGvDz0ZAgMBAAECggEASnPxlBduBUwubKsrVtoe1Wg0OBheYQaYo0DuCK3i3UNY
    Vw2LhyQlmbZq0hmk/er0AvWe+PK6iBNwE4Qjsxqfb+lHKPbKxooAm2A51O+hPcLY
    KISbA6XY+1ieKTK2S7ad2Qh356RcWRzCIIBK2tr8/u5iSB7VZj+Gxyz001pEC7B7
    2ZlfGVilA4QkhC4V23c6s3h4q525cOJFeXvvVvKpoenR6r/pa5/I4/ubv5/Kgqqi
    VJ2f3FjQfDMu6iN4V4Nx8Y2mrzAmsn9syPdan27YiwEilzNBo2MyZyslsQ8qQstc
    6A7ahUNpw+GzV7M42/jlCByzYWz9vzgNoKKCLLMEAQKBgQD2/gExq5QWZpxe8i7i
    k2qqOMgmmW6svF1Y/7xIxJ+j6ruhCoGY+uSXT9tQYmPZitTFjppYIgKzbwwG+1wo
    JXI/jbqHqyAiRO2ygzYzsTGrM+FAyHE0Wb0W+XnLLH3o261D/SzYFRlLrTCE5ouC
    ZBeDPFAh/jp75grgQpDnWUVoeQKBgQDcTqUlNzD+d3DQwmJHiHLleEU7IQMpbl00
    lewgbxqJQLs7qIVnzZK2b55ScKe9qHJ/tBj4kJLudi2dMffrDax4k+ocARZqNodp
    Kwv6uP/C4G+DwRlrxg3oAvuHkZ/0e1Oa+35zk0CubCGVtHcAkVcHN6cchk9ESOhc
    WoZX9RyRoQKBgAv+9DHkYnHgE/IskwhgHosb7OSrCQwMrf/3k755BkPgz7IXn4m9
    jcKnl0BFNxJGwuTBc0+af0UVvKDOLoCoqO7bRFb4gbwIWv8TjlteXMoy39rUoWLo
    hN2LylWK2KapnLWzoyzvgWYCiFu8EsSHdfjiwgWUomSIHLkdoooJ9OwJAoGAGsLu
    6rNmnzKxIJrMR3Y6xscyWblr4eeHKPEhSttUNOIJHHkfI3nkXYb3i3ol1jMVHZAq
    DF+7iX4Pkm3UeNgjYE5PfPFg4KwZDNxuyxkX8HtE8JNPXDklzU43ccNt08v7XvM3
    7CAyFj4KYl4Wqpn9IWJQSXXDQT8+AqH4eczLmKECgYEAz1o2xeWgFY/i5w1oRJv9
    lxzSeaiUdeNBtCUoLS9E1Abm0Uv+k/QwYQufkHKzIGFdwPacEtmpqTf5WUw4AmCS
    L5xA+udoYpj99RpHXN3Gbahz6DCLoBuBWDlfF2q3q/7qa6lD3YX7gv+iWSF/C4Zf
    Zh148DyCvEJ31aqKBTJkWcs=
    -----END PRIVATE KEY-----
